import os

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_BASE_URL = os.getenv("OPENAI_BASE_URL", "https://cloud.yiyongai.cn/v1")
AI_MODEL = os.getenv("AI_MODEL", "claude-sonnet-5")
EXCHANGE = os.getenv("EXCHANGE", "okx")
SYMBOLS = os.getenv("SYMBOLS", "BTC/USDT,ETH/USDT,SOL/USDT")
DATA_DIR = os.getenv("DATA_DIR", "./data")
REPORT_DIR = os.getenv("REPORT_DIR", "./reports")
DB_PATH = os.getenv("DB_PATH", "./data/finagent.db")
FETCH_INTERVAL_MIN = int(os.getenv("FETCH_INTERVAL_MIN", "15"))
ANALYZE_INTERVAL_MIN = int(os.getenv("ANALYZE_INTERVAL_MIN", "60"))
BACKTEST_LOOKBACK_DAYS = int(os.getenv("BACKTEST_LOOKBACK_DAYS", "365"))
RISK_MAX_POSITION = float(os.getenv("RISK_MAX_POSITION", "0.06"))
RISK_MAX_TOTAL = float(os.getenv("RISK_MAX_TOTAL", "0.5"))
RISK_STOP_LOSS = float(os.getenv("RISK_STOP_LOSS", "-0.08"))
RISK_TRAILING_STOP = float(os.getenv("RISK_TRAILING_STOP", "0.05"))
RISK_MAX_DRAWDOWN = float(os.getenv("RISK_MAX_DRAWDOWN", "-0.15"))
AI_MIN_CONFIDENCE = float(os.getenv("AI_MIN_CONFIDENCE", "0.6"))
AI_BUY_THRESHOLD = float(os.getenv("AI_BUY_THRESHOLD", "0.7"))
AI_SELL_THRESHOLD = float(os.getenv("AI_SELL_THRESHOLD", "-0.3"))
HOST = os.getenv("HOST", "0.0.0.0")
PORT = int(os.getenv("PORT", "8000"))